server:
  port: 8001
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  mapper-locations: classpath:eqlee/ctm/user/dao/mapper/*.xml
spring:
  profiles:
    active: test
  application:
    name: service-user
app:
  workerId: 9
  dataCenterId: 1
