ws:
  ip: 10.36.142.73
  port: 8899
server:
  port: 8008
  max-http-header-size: 102400
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  mapper-locations: classpath:eqlee/ctm/msg/*/dao/mapper/*.xml
spring:
  profiles:
    active: dev
  application:
    name: service-msg
  jmx:
    enabled: false
app:
  workerId: 9
  dataCenterId: 1
