server:
  port: 8002
  max-http-header-size: 102400
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  mapper-locations: classpath:eqlee/ctm/apply/*/dao/mapper/*.xml
spring:
  profiles:
    active: dev
  application:
    name: service-apply
  jmx:
    enabled: false
app:
  workerId: 9
  dataCenterId: 1
