server:
  port: 8002
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  mapper-locations: classpath:com/yq/apply/*/dao/mapper/*.xml
spring:
  profiles:
    active: test
  application:
    name: service-apply
app:
  workerId: 9
  dataCenterId: 1
