server:
  port: 8000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  mapper-locations: classpath:com/yq/resource/*/dao/mapper/*.xml
spring:
  profiles:
    active: test
  application:
    name: service-resource
