server:
  port: 8005
  max-http-header-size: 102400
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  mapper-locations: classpath:eqlee/ctm/report/*/dao/mapper/*.xml
spring:
  profiles:
    active: dev
  application:
    name: service-report
  jmx:
    enabled: false
app:
  workerId: 9
  dataCenterId: 1
