server:
  port: 8003
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  mapper-locations: classpath:eqlee/ctm/api/*/dao/mapper/*.xml
spring:
  profiles:
    active: dev
  application:
    name: service-api
  jmx:
    enabled: false
app:
  workerId: 9
  dataCenterId: 1
api:
  userIp: 192.168.0.253
  port: 9092
resourceApi:
  port: 9091
  path: resource
applyApi:
  port: 9090
  path: apply
